bulletin:
  institution: 'AGRHYMET CCR-AOS'
  title: 'Bulletin de prévision hydrologique'
  number: '001-2026'
  issue_date: '2026-04-27'
  validity_date: '2026-05-03'
  forecast_horizon_days: 5

Data_Processing:
    country_code: 'NGA'
    countries_shp : "D:/CCR_AOS/ACTIVITES/AGRHYMET/2026/DCEM/Dev/bulletin/hydro_bulletin/data/statics/was_contries.shp"
    subbassins_shp : "D:/CCR_AOS/ACTIVITES/AGRHYMET/2026/DCEM/Dev/bulletin/hydro_bulletin/data/statics/subbasins.shp"
    rivers_shp : "D:/CCR_AOS/ACTIVITES/AGRHYMET/2026/DCEM/PRESASS/PRESASS2026/data/statics/was_rivers.shp"
    stations_shp : NULL
    stations_csv : "D:/CCR_AOS/ACTIVITES/AGRHYMET/2026/DCEM/Dev/bulletin/hydro_bulletin/data/statics/abn_outlets_lev5.csv"
    
figures:
    output_path: "D:/CCR_AOS/ACTIVITES/AGRHYMET/2026/DCEM/Dev/bulletin/hydro_bulletin/outputs/figures"
    logo_path: NULL
    max_risk_map:
        width: 10
        height: 8
    daily_risk_map:
        facet_nrow: 2
        width: 16
        height: 6
    hydrograph:
        width: 14
        height: 10

outputs:
  pdf: true
  word: true
  html: true
  language: 'fr'
  
